
[[protocols]]
name = "LG"
protocol = "nec"
#variant = "necx"

[protocols.scancodes]
# table lg, type nec
0x411 = "KEY_1"
0x412 = "KEY_2"
0x413 = "KEY_3"
0x414 = "KEY_4"
0x415 = "KEY_5"
0x416 = "KEY_6"
0x417 = "KEY_7"
0x418 = "KEY_8"
0x419 = "KEY_9"
0x410 = "KEY_0"
0x453 = "KEY_LIST"
#0x41a = "Q_View"
0x402 = "KEY_VOLUMEUP"
0x403 = "KEY_VOLUMEDOWN"
#0x400 = "P.+"
#0x401 = "P.-"
0x443 = "KEY_MENU"
0x45b = "KEY_EXIT"
0x4aa = "KEY_INFO"
#0x4ab = "KEY_GUIDE"
0x444 = "KEY_OK"
0x440 = "KEY_UP"
0x441 = "KEY_DOWN"
0x406 = "KEY_RIGHT"
0x407 = "KEY_LEFT"
0x428 = "KEY_ENTER"
0x41e = "KEY_FAVORITES"
#0x450 = "TV/PC"
#0x000 = "INPUT"
0x408 = "KEY_POWER"
#0x4f0 = "TV/RADIO"
0x420 = "KEY_TEXT"
#0x40a = "I/II"
0x409 = "KEY_MUTE"
0x472 = "KEY_RED"
#0x471 = "green/STOP"
#0x463 = "yellow/PLAY"
#0x461 = "blu/PAUSE"
#0x445 = "Q.MENU"
#0x421 = "T.OPT/<<"
0x439 = "KEY_SUBTITLE"
#0x41e = "MARK"

